# Generated by Django 4.2.3 on 2023-08-11 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vicky', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=120)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vicky.test')),
            ],
            options={
                'db_table': 'test2',
            },
        ),
    ]
