# Generated by Django 4.2.3 on 2023-08-17 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('age', models.CharField(max_length=100)),
                ('alternateno', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('panno', models.CharField(max_length=100)),
                ('aadhhaarno', models.CharField(max_length=100)),
                ('nomieename', models.CharField(max_length=100)),
                ('nomieeage', models.CharField(max_length=100)),
                ('nomieerelationship', models.CharField(max_length=100)),
                ('nomieeaddress', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('dimension', models.CharField(max_length=100)),
                ('moblieno', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('downpayment', models.CharField(max_length=100)),
                ('siterefer', models.CharField(max_length=100)),
                ('modeofpay', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('chequeno', models.CharField(max_length=100)),
                ('paydate', models.DateField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('seniorityno', models.CharField(max_length=100)),
                ('amno', models.CharField(max_length=100)),
                ('receiptno', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=100)),
                ('shotcode', models.CharField(max_length=100)),
                ('dp_price', models.CharField(max_length=100)),
                ('first_install', models.CharField(max_length=100)),
                ('second_install', models.CharField(max_length=100)),
                ('third_install', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='static/images/')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membername', models.CharField(max_length=120)),
                ('dimension', models.CharField(max_length=120)),
                ('amount', models.CharField(max_length=120)),
                ('modeofpay', models.CharField(max_length=120)),
                ('chequeno', models.CharField(max_length=120)),
                ('bank', models.CharField(max_length=120)),
                ('branch', models.CharField(max_length=120)),
                ('paydate', models.DateField(max_length=120)),
                ('paystatus', models.CharField(max_length=120)),
                ('dateofreceipt', models.DateField(max_length=120)),
                ('seniorityno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.newbooking')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familymemname', models.CharField(max_length=100)),
                ('familymemage', models.CharField(max_length=10)),
                ('familymemrelation', models.CharField(max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.newbooking')),
            ],
        ),
    ]
