# Generated by Django 4.2.3 on 2023-08-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbooking',
            name='membername',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
