# Generated by Django 4.2.3 on 2023-08-11 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familymemname', models.CharField(max_length=100)),
                ('familymemage', models.CharField(max_length=10)),
                ('familymemrelation', models.CharField(max_length=100)),
                ('membername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.newbooking')),
            ],
        ),
    ]
