# Generated by Django 4.2.3 on 2023-08-18 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_user_newbooking_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newbooking',
            name='membername',
        ),
    ]
