# Generated by Django 4.2.3 on 2023-08-13 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_project_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seniorityno', models.CharField(max_length=120)),
                ('dimension', models.CharField(max_length=120)),
                ('amount', models.CharField(max_length=120)),
                ('modeofpay', models.CharField(max_length=120)),
                ('chequeno', models.CharField(max_length=120)),
                ('bank', models.CharField(max_length=120)),
                ('branch', models.CharField(max_length=120)),
                ('paydate', models.DateField(max_length=120)),
                ('paystatus', models.CharField(max_length=120)),
                ('dateofreceipt', models.DateField(max_length=120)),
                ('membername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.newbooking')),
            ],
        ),
    ]
