# Generated by Django 4.2.3 on 2023-08-18 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_role_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='membername',
            new_name='username',
        ),
    ]
