# Generated by Django 4.2.3 on 2023-08-18 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_family_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
