# Generated by Django 4.2.3 on 2023-08-25 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newbooking',
            name='amno',
        ),
        migrations.RemoveField(
            model_name='newbooking',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='newbooking',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='newbooking',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='newbooking',
            name='chequeno',
        ),
        migrations.RemoveField(
            model_name='newbooking',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='newbooking',
            name='downpayment',
        ),
        migrations.RemoveField(
            model_name='newbooking',
            name='modeofpay',
        ),
        migrations.RemoveField(
            model_name='newbooking',
            name='nomieeaddress',
        ),
        migrations.RemoveField(
            model_name='newbooking',
            name='nomieeage',
        ),
        migrations.RemoveField(
            model_name='newbooking',
            name='nomieename',
        ),
        migrations.RemoveField(
            model_name='newbooking',
            name='nomieerelationship',
        ),
        migrations.RemoveField(
            model_name='newbooking',
            name='paydate',
        ),
        migrations.RemoveField(
            model_name='newbooking',
            name='project',
        ),
        migrations.RemoveField(
            model_name='newbooking',
            name='receiptno',
        ),
        migrations.RemoveField(
            model_name='newbooking',
            name='seniorityno',
        ),
        migrations.RemoveField(
            model_name='newbooking',
            name='siterefer',
        ),
        migrations.RemoveField(
            model_name='newbooking',
            name='total',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100)),
                ('dimension', models.CharField(max_length=100)),
                ('downpayment', models.CharField(max_length=100)),
                ('siterefer', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nomiee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomieename', models.CharField(max_length=100)),
                ('nomieeage', models.CharField(max_length=100)),
                ('nomieerelationship', models.CharField(max_length=100)),
                ('nomieeaddress', models.CharField(max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeofpay', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('chequeno', models.CharField(max_length=100)),
                ('paydate', models.DateField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('seniorityno', models.CharField(max_length=100)),
                ('amno', models.CharField(max_length=100)),
                ('receiptno', models.CharField(max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
