# Generated by Django 4.2.3 on 2023-08-26 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_remove_newbooking_amno_remove_newbooking_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('age', models.CharField(max_length=100)),
                ('alternateno', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('panno', models.CharField(max_length=100)),
                ('aadhhaarno', models.CharField(max_length=100)),
                ('moblieno', models.CharField(max_length=100)),
                ('poision', models.CharField(max_length=120)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
